#!/usr/bin/env python3
from pathlib import Path

import click

from gen_redox_lib.gen_helpers import (
    download_and_extract,
    format_python_files,
    process_files,
    rmrf,
)
from gen_redox_lib.gen_helpers.get_spec import DEFAULT_SPEC_URL

PACKAGE_DIR = Path(__file__).parent.resolve()
CACHE_DIR = PACKAGE_DIR / "cache"
TEMPLATE_DIR = PACKAGE_DIR / "templates"
VENDOR_DIR = PACKAGE_DIR / "vendor"
# gen_redox_lib and redox are checked out as siblings; generated code lands in
# the redox package directory.
LIB_DEST_DIR = (PACKAGE_DIR / ".." / ".." / "redox" / "redox").resolve()

# Hand-maintained files that live in the redox repo and must survive a regen.
# abstract_base.py and factory.py are copied in fresh from vendor/ each run.
_KEEP_ON_WIPE = {Path("README.md"), Path("__init__.py"), Path("py.typed")}
_VENDORED_INTO_PACKAGE = ("abstract_base.py", "factory.py", "field_types.py", "py.typed")


@click.command()
@click.option(
    "--dst",
    "-d",
    default=LIB_DEST_DIR,
    show_default=True,
    type=click.Path(file_okay=False, dir_okay=True, writable=True, resolve_path=True, path_type=Path),
    help=(
        "Directory the redox library is generated into. Its contents (except a "
        "few hand-maintained files) are deleted first."
    ),
)
@click.option(
    "--cache-dir",
    "-c",
    default=CACHE_DIR,
    type=click.Path(file_okay=False, dir_okay=True, writable=True, resolve_path=True, path_type=Path),
    help="Scratch directory the schema bundle is unpacked into.",
)
@click.option("--spec-url", default=DEFAULT_SPEC_URL, show_default=True, type=str)
@click.option(
    "--redox-session",
    default=None,
    help="Redox dashboard session cookie for --force-download (or set $REDOX_SESSION).",
)
@click.option(
    "--force-download",
    "-f",
    is_flag=True,
    help="Fetch a fresh schema bundle from the Redox dashboard and refresh the vendored copy.",
)
def main(dst: Path, cache_dir: Path, spec_url: str, redox_session: str | None, force_download: bool) -> None:
    """Generate Pydantic models from the Redox JSON schema."""
    extracted = download_and_extract(
        cache_dir,
        force_download=force_download,
        spec_url=spec_url,
        session=redox_session,
    )

    rmrf(dst, exclude=_KEEP_ON_WIPE)
    dst.mkdir(parents=True, exist_ok=True)

    process_files(
        extracted_folder=extracted,
        dst=dst,
        directories=sorted(d.name for d in extracted.iterdir() if d.is_dir()),
        jinja_template_dir=TEMPLATE_DIR,
    )

    for name in _VENDORED_INTO_PACKAGE:
        src = VENDOR_DIR / name
        if src.exists():
            (dst / name).write_bytes(src.read_bytes())

    _copy_tree(VENDOR_DIR / "tests", dst.parent / "tests")
    _write_version_files(dst)

    format_python_files(dst)


def _resolve_version(repo_root: Path) -> str:
    """Read the redox package version from its pyproject, defaulting to 0.0.0."""
    pyproject = repo_root / "pyproject.toml"
    if pyproject.exists():
        for line in pyproject.read_text().splitlines():
            stripped = line.strip()
            if stripped.startswith("version") and "=" in stripped:
                return stripped.split("=", 1)[1].strip().strip('"').strip("'")
    return "0.0.0"


def _write_version_files(dst: Path) -> None:
    version = _resolve_version(dst.parent)
    (dst / "__init__.py").write_text(
        f'# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #\n__version__ = "{version}"\n'
    )
    (dst.parent / "tests").mkdir(parents=True, exist_ok=True)
    (dst.parent / "tests" / "test_version.py").write_text(
        "# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #\n"
        "from redox import __version__\n\n\n"
        "def test_version():\n"
        f'    assert __version__ == "{version}"\n'
    )


def _copy_tree(src: Path, dst: Path) -> None:
    if not src.exists():
        return
    for item in src.rglob("*"):
        target = dst / item.relative_to(src)
        if item.is_dir():
            target.mkdir(parents=True, exist_ok=True)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(item.read_bytes())


if __name__ == "__main__":
    main()
