#!/usr/bin/env python3
"""Post-regeneration step: open a PR on ``redox`` or heartbeat ``gen_redox_lib``.

Run ``gen-redox-lib`` first to regenerate ``../redox/redox``. If that produced a
diff, this bumps the patch version, commits it on a dated branch, pushes, and
opens a PR with ``gh``. If not, it force-pushes a timestamp to this repo's
``schema-check-heartbeat`` branch so GitHub doesn't disable the weekly cron for
60 days of inactivity.
"""

import tomllib
from datetime import UTC, datetime
from pathlib import Path
from subprocess import CalledProcessError, run

import click

from gen_redox_lib.generate import LIB_DEST_DIR
from gen_redox_lib.utils import temp_chdir

REDOX_REPO = LIB_DEST_DIR.parent
GEN_REPO = Path(__file__).resolve().parents[1]
# Branch this repo force-pushes a marker to when a scheduled run finds nothing,
# so GitHub doesn't disable the weekly workflow for 60 days of inactivity.
HEARTBEAT_BRANCH = "schema-check-heartbeat"


def _git(*args: str, capture: bool = False, cwd: Path = REDOX_REPO) -> str:
    with temp_chdir(cwd):
        proc = run(["git", *args], capture_output=capture, text=True, check=True)
    return (proc.stdout or "").strip() if capture else ""


def count_changes() -> int:
    status = _git("status", "--short", capture=True)
    return len([line for line in status.splitlines() if line.strip()])


def bump_version() -> str:
    """Patch-bump the redox version and rewrite the files that echo it."""
    pyproject = REDOX_REPO / "pyproject.toml"
    data = tomllib.loads(pyproject.read_text())
    major, minor, patch = (int(p) for p in data["project"]["version"].split("."))
    new_version = f"{major}.{minor}.{patch + 1}"

    text = pyproject.read_text()
    old_line = f'version = "{major}.{minor}.{patch}"'
    text = text.replace(old_line, f'version = "{new_version}"', 1)
    pyproject.write_text(text)

    (LIB_DEST_DIR / "__init__.py").write_text(
        f'# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #\n__version__ = "{new_version}"\n'
    )
    (REDOX_REPO / "tests" / "test_version.py").write_text(
        "# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #\n"
        "from redox import __version__\n\n\n"
        "def test_version():\n"
        f'    assert __version__ == "{new_version}"\n'
    )

    with temp_chdir(REDOX_REPO):
        run(["uv", "lock"], check=False)
    return new_version


def open_pr(num_changes: int) -> None:
    today = datetime.now(tz=UTC).date().isoformat()
    branch = f"lib_gen_{today}"
    with temp_chdir(REDOX_REPO):
        run(["git", "checkout", "-b", branch], check=True)
        run(["git", "add", "--all"], check=True)
        run(["git", "commit", "-m", f"{today}: {num_changes} generated changes"], check=True)
        run(["git", "push", "--set-upstream", "origin", branch], check=True)
        run(
            [
                "gh",
                "pr",
                "create",
                "--base",
                "main",
                "--title",
                f"Schema regeneration ({today})",
                "--body",
                f"Automated regeneration from the Redox schema: {num_changes} changed lines.",
            ],
            check=True,
        )
    click.echo(f"Opened PR from {branch}")


def heartbeat() -> None:
    """Keep this repo's weekly schedule alive when there's no schema drift.

    Force-pushes a single timestamp commit to ``HEARTBEAT_BRANCH`` in
    *gen_redox_lib* (where the cron lives). Pushing to any branch counts as
    repository activity, and using a throwaway branch keeps ``main`` and its
    protections untouched.
    """
    (GEN_REPO / ".heartbeat").write_text(datetime.now(tz=UTC).isoformat() + "\n")
    with temp_chdir(GEN_REPO):
        run(["git", "add", "--force", ".heartbeat"], check=True)
        run(["git", "commit", "--no-verify", "-m", "chore: schema-check heartbeat"], check=True)
        run(["git", "push", "--force", "origin", f"HEAD:refs/heads/{HEARTBEAT_BRANCH}"], check=True)
        run(["git", "reset", "--hard", "HEAD~1"], check=True)
    click.echo(f"Pushed heartbeat to {HEARTBEAT_BRANCH}.")


@click.command()
@click.option("--version", "version_only", is_flag=True, help="Only bump the version files.")
def main(version_only: bool) -> None:
    if version_only:
        bump_version()
        return
    try:
        num_changes = count_changes()
        if num_changes:
            click.echo(f"{num_changes} changed lines; opening a PR.")
            bump_version()
            open_pr(num_changes)
        else:
            heartbeat()
    except CalledProcessError as err:
        msg = f"Command failed: {err.cmd}"
        raise SystemExit(msg) from err


if __name__ == "__main__":
    main()
