#!/usr/bin/env python3
"""Open (or heartbeat) a PR against the redox repo after regeneration.

Run ``gen-redox-lib`` first to regenerate ``../redox/redox``; this then bumps the
patch version, commits the diff on a dated branch, pushes, and opens a PR with
``gh``. With no diff it optionally writes a heartbeat commit so GitHub doesn't
disable the weekly schedule for inactivity.
"""

import sys
import tomllib
from datetime import UTC, datetime
from pathlib import Path
from subprocess import CalledProcessError, run

import click

from gen_redox_lib.generate import LIB_DEST_DIR
from gen_redox_lib.utils import temp_chdir

REDOX_REPO = LIB_DEST_DIR.parent
HEARTBEAT_THRESHOLD_DAYS = 45


def _git(*args: str, capture: bool = False, cwd: Path = REDOX_REPO) -> str:
    with temp_chdir(cwd):
        proc = run(["git", *args], capture_output=capture, text=True, check=True)
    return (proc.stdout or "").strip() if capture else ""


def count_changes() -> int:
    status = _git("status", "--short", capture=True)
    return len([line for line in status.splitlines() if line.strip()])


def bump_version() -> str:
    """Patch-bump the redox version and rewrite the files that echo it."""
    pyproject = REDOX_REPO / "pyproject.toml"
    data = tomllib.loads(pyproject.read_text())
    major, minor, patch = (int(p) for p in data["project"]["version"].split("."))
    new_version = f"{major}.{minor}.{patch + 1}"

    text = pyproject.read_text()
    old_line = f'version = "{major}.{minor}.{patch}"'
    text = text.replace(old_line, f'version = "{new_version}"', 1)
    pyproject.write_text(text)

    (LIB_DEST_DIR / "__init__.py").write_text(
        f'# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #\n__version__ = "{new_version}"\n'
    )
    (REDOX_REPO / "tests" / "test_version.py").write_text(
        "# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #\n"
        "from redox import __version__\n\n\n"
        "def test_version():\n"
        f'    assert __version__ == "{new_version}"\n'
    )

    with temp_chdir(REDOX_REPO):
        run(["uv", "lock"], check=False)
    return new_version


def open_pr(num_changes: int) -> None:
    today = datetime.now(tz=UTC).date().isoformat()
    branch = f"lib_gen_{today}"
    with temp_chdir(REDOX_REPO):
        run(["git", "checkout", "-b", branch], check=True)
        run(["git", "add", "--all"], check=True)
        run(["git", "commit", "-m", f"{today}: {num_changes} generated changes"], check=True)
        run(["git", "push", "--set-upstream", "origin", branch], check=True)
        run(
            [
                "gh",
                "pr",
                "create",
                "--base",
                "main",
                "--title",
                f"Schema regeneration ({today})",
                "--body",
                f"Automated regeneration from the Redox schema: {num_changes} changed lines.",
            ],
            check=True,
        )
    click.echo(f"Opened PR from {branch}")


def days_since_last_commit() -> int:
    last = int(_git("log", "-1", "--format=%ct", cwd=REDOX_REPO, capture=True))
    return (datetime.now(tz=UTC) - datetime.fromtimestamp(last, tz=UTC)).days


def heartbeat() -> None:
    """Keep the weekly schedule alive during long stretches with no schema drift."""
    if days_since_last_commit() < HEARTBEAT_THRESHOLD_DAYS:
        click.echo("No changes and repo is active; nothing to do.")
        return
    marker = REDOX_REPO / ".gen_redox_lib_heartbeat"
    marker.write_text(datetime.now(tz=UTC).isoformat() + "\n")
    with temp_chdir(REDOX_REPO):
        run(["git", "add", str(marker)], check=True)
        run(["git", "commit", "-m", "chore: schema-check heartbeat"], check=True)
        run(["git", "push"], check=True)
    click.echo("Wrote heartbeat commit.")


@click.command()
@click.option("--version", "version_only", is_flag=True, help="Only bump the version files.")
def main(version_only: bool) -> int:
    if version_only:
        bump_version()
        return 0
    try:
        num_changes = count_changes()
        if num_changes:
            click.echo(f"{num_changes} changed lines; opening a PR.")
            bump_version()
            open_pr(num_changes)
        else:
            heartbeat()
    except CalledProcessError as err:
        click.echo(f"Command failed: {err.cmd}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
