import re
import shutil
from collections.abc import Callable, Iterator
from pathlib import Path
from subprocess import run

import click
from jinja2 import Environment, FileSystemLoader, select_autoescape

from .common_klasses import CommonKlassKeeper
from .parse_spec import parse_and_build_models
from .types import TemplateInfo

_CLASS_DEF_RE = re.compile(r"^class (\w+)\(", re.MULTILINE)
_FIELD_LINE_RE = re.compile(
    r"^(?P<indent> {4})(?P<name>\w+): (?P<annotation>.+?)(?P<rest> = Field\()",
    re.MULTILINE,
)
_REBUILD_RE = re.compile(r"^(\w+)\.model_rebuild\(\)", re.MULTILINE)


def process_files(
    *,
    extracted_folder: Path,
    dst: Path,
    directories: list[str],
    jinja_template_dir: Path,
) -> None:
    # Create the Jinja environment and template
    jinja_env = Environment(
        loader=FileSystemLoader(jinja_template_dir),
        autoescape=select_autoescape(),
        trim_blocks=True,
        lstrip_blocks=True,
    )

    commons = CommonKlassKeeper()

    # Count the number of files we'll be processing so click can make a progressbar
    num_files = sum(len(list((extracted_folder / d).iterdir())) for d in directories)
    # Add to the count: One generic file per directory + "common" types file
    num_files += len(directories) + 1

    # Create the progressbar and an updater function
    with click.progressbar(
        length=num_files,
        label=f"Generating {num_files} Python files",
        item_show_func=lambda f: f,
    ) as bar:

        def update_bar(file_name: str) -> None:
            bar.update(1, file_name)

        for directory in directories:
            parsed_generator = parse_and_build_models(spec_dir=extracted_folder / directory)
            write_py_files(
                lib_dest_dir=dst,
                jinja_env=jinja_env,
                progressbar_updater=update_bar,
                template_info_generator=commons.store_and_yield_templates(parsed_generator),
            )

        # Generics and commons
        write_py_files(
            lib_dest_dir=dst,
            jinja_env=jinja_env,
            progressbar_updater=update_bar,
            template_info_generator=commons.templates,
        )

    privatize_generic_module(dst / "generic")

    click.echo("Done")
    click.echo(f"redox library files generated at {dst}")


def _noop(_: str) -> None:
    pass


def write_py_files(
    lib_dest_dir: Path,
    jinja_env: Environment,
    template_info_generator: Iterator[TemplateInfo],
    progressbar_updater: Callable[[str], None] = _noop,
) -> None:
    """Write the generated files for a single directory.

    :param lib_dest_dir: The directory where the generated library Python files
        will be written.
    :param jinja_env: The Jinja2 environment that can load the appropriate
        template for each ``TemplateInfo`` object.
    :param template_info_generator:
    :param progressbar_updater: A function for updating the progress on writing
        the generated files. Should take a filename string as the only argument.
    """

    for template_info in template_info_generator:
        # Make sure the destination dir exists
        (lib_dest_dir / template_info.dir_name).mkdir(exist_ok=True)

        template = jinja_env.get_template(template_info.jinja_template_file_name)
        model_path = lib_dest_dir / template_info.dir_name / template_info.file_name
        model_path.write_text(template.render(**template_info.as_dict()))

        progressbar_updater(template_info.file_name)

        # Add all event type classes as imports in the __init__.py for easier importing
        init_path = lib_dest_dir / template_info.dir_name / "__init__.py"
        if not init_path.exists():
            init_path.write_text(
                "# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #\n# ruff: noqa: F401\n"
            )
        if template_info.add_event_types_to_init:
            module = template_info.file_name.rsplit(".", 1)[0]
            with init_path.open("a") as init_file:
                init_file.writelines(
                    f"from .{module} import {event_class.full_name}\n"
                    for event_class in template_info.event_type_classes
                )


SHARED_RUFF_CONFIG = (Path(__file__).resolve().parent.parent / "vendor" / "ruff.toml").read_text()


def privatize_generic_module(generic_dir: Path) -> None:
    """Give every class in ``generic/types.py`` a private name + public alias.

    Pydantic v2 rejects a model whose field name matches an in-scope type name
    (``PydanticUserError: field name clashing with a type annotation``). The
    ``generic`` package hits this constantly - e.g. ``class Address`` with an
    ``Address`` field elsewhere. Renaming the *class* to ``_Address`` (with a
    module-level ``Address = _Address`` alias) sidesteps the clash while keeping
    ``redox.generic.types.Address`` and ``isinstance`` checks working. Field
    names stay bare, so the public API matches pyredox 1.0.4.
    """
    types_py = generic_dir / "types.py"
    if not types_py.exists():
        return

    source = types_py.read_text()
    class_names = sorted(set(_CLASS_DEF_RE.findall(source)), key=len, reverse=True)
    ref_res = {name: re.compile(rf"(?<!\w){re.escape(name)}\b") for name in class_names}

    def privatize_annotation(match: re.Match) -> str:
        annotation = match["annotation"]
        for name in class_names:
            annotation = ref_res[name].sub(f"_{name}", annotation)
        return f"{match['indent']}{match['name']}: {annotation}{match['rest']}"

    source = _FIELD_LINE_RE.sub(privatize_annotation, source)
    source = _CLASS_DEF_RE.sub(r"class _\1(", source)
    source = _REBUILD_RE.sub(r"_\1.model_rebuild()", source)

    aliases = "\n".join(f"{name} = _{name}" for name in sorted(class_names))
    source = f"{source}\n\n# Public aliases (see privatize_generic_module).\n{aliases}\n"
    types_py.write_text(source)

    # The generic event modules import these classes as ``generic.<Name>``; point
    # them at the real (private) classes.
    event_modules = []
    for module in sorted(generic_dir.glob("*.py")):
        if module.name in {"types.py", "__init__.py"}:
            continue
        event_modules.append(module.stem)
        text = module.read_text()
        for name in class_names:
            text = re.sub(rf"\bgeneric\.{re.escape(name)}\b", f"generic._{name}", text)
        module.write_text(text)

    # Re-export the per-data-model submodules so factory.from_redox_to_generic
    # can do getattr(redox.generic, "PatientAdmin").
    init_py = generic_dir / "__init__.py"
    init_py.write_text(
        "# ----  AUTO-GENERATED BY gen_redox_lib. DO NOT MODIFY MANUALLY!!  ---- #\n"
        "# ruff: noqa: F401\n" + "".join(f"from . import {name}\n" for name in event_modules) + "from . import types\n"
    )


def format_python_files(target_dir: Path) -> None:
    """Make the generated tree pass ruff, then verify it.

    The generator owns the redox repo's lint config: it (re)writes ``.ruff.toml``
    at the repo root from the vendored template, runs ``ruff check --fix`` +
    ``ruff format``, then a final strict ``ruff check`` that raises if anything
    remains. This is what lets ``handle_updates.yml`` trust that a regenerated
    tree is ship-ready before opening a PR.
    """
    target_dir = target_dir.resolve()
    repo_root = target_dir.parent
    ruff = shutil.which("ruff")
    if ruff is None:  # pragma: no cover - ruff is a hard dependency
        msg = "`ruff` is not on PATH; it is a runtime dependency of gen_redox_lib."
        raise RuntimeError(msg)

    (repo_root / ".ruff.toml").write_text(SHARED_RUFF_CONFIG)

    click.echo("Auto-fixing generated files with ruff")
    run([ruff, "check", "--fix", "--unsafe-fixes", "--quiet", str(repo_root)], check=False)
    click.echo("Formatting generated files with ruff")
    run([ruff, "format", "--quiet", str(repo_root)], check=True)

    click.echo("Verifying the generated tree is lint-clean")
    run([ruff, "check", str(repo_root)], check=True)
