on:
  workflow_dispatch:
  schedule:
    # Run this every Sunday at 7:15
    - cron: '15 7 * * 0'

jobs:
  check_for_updated_schema:
    runs-on: ubuntu-latest
    steps:
      # Check out and set up gen_redox_lib
      - name: Checkout lib generator
        uses: actions/checkout@v3
        with:
          path: gen_redox_lib

      - name: Install Python and Poetry
        uses: mmabey/action-setup-python@v0.3.1
        with:
          poetry-install-args: "-vvv --remove-untracked --directory=gen_redox_lib"
          python-version: "3.10"  # String keeps this from being interpreted as a float

      # Check out and set up redox library
      - name: Checkout redox repo
        uses: actions/checkout@v3
        with:
          path: redox
          repository: mmabey/redox
          ref: main

      - name: Install Python and Poetry
        uses: mmabey/action-setup-python@v0.3.1
        with:
          poetry-install-args: "-vvv --remove-untracked --directory=redox"
          python-version: "3.7"

      # Run generator, handle updates
      - name: Generate fresh version of library
        working-directory: gen_redox_lib/gen_redox_lib
        run: poetry run python generate.py --force-download

      - name: Open PR if there are changes
        working-directory: gen_redox_lib/gen_redox_lib
        run: poetry run python pull_request.py
